# Generated by Django 3.2.8 on 2021-11-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='City',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
    ]
